site:
  title: JUDO Community
  url: https://documentation.judo.technology
  start_page: ROOT:getting-started/00_introduction.adoc

content:
  sources:
  - url: .
    branches: HEAD
    version: true
    start_path: docs

ui:
  bundle:
    url: ./ui/build/ui-bundle.zip
  supplemental_files: ./antora-lunr-ui

output: 
  clean: true
  dir: ./build

asciidoc:
  attributes:
    page-pagination: true
  extensions:
  - asciidoctor-kroki
