= IDE support and setup

:idprefix:
:idseparator: -

JUDO applications can be developed with any or no IDE. However, to achieve a seamless developer experience, we ship first party
IDE plugins which come with the following features:

- Syntax highlighting
- Intellisense capabilities
- Refactor tools
- Diagram generation capabilities

IDEs with first-party JSL language support:

- Eclipse
- IntelliJ IDEA (WIP)
- VSCode (WIP)

> Before starting with any IDE, make sure you check the xref:ROOT:getting-started/01_system-requirements.adoc[System Requirements] page!

== Eclipse

Installing the JSL DSL plugin in Eclipse:

- Click "Help" on the top of the application
- Select "Install new software..."
- In the "Work with" input box, paste the following URL:

TODO

== Intellij IDEA

Our IntelliJ IDEA plugin is a TextMate plugin, which currently only supports syntax highlighting.

Additional functionality such as intellisense is in the works. In fact the support for the platform should be expected
to be improved continuously so stay tuned for updates!

Installation instructions could be found in the plugin's https://github.com/BlackBeltTechnology/jsl.tmbundle/blob/develop/doc/install-idea.adoc[Github Repository].

== VSCode

Plugin development for this platform is still in progress. Stay tuned for updates!
