= IDE support and setup

:idprefix:
:experimental:
:idseparator: -

JUDO applications can be developed with any or no IDE. However, to achieve a seamless developer experience, we ship first party
IDE plugins which come with the following features:

- Syntax highlighting
- IntelliSense capabilities
- Refactor tools
- Diagram generation capabilities

IDEs with first-party JSL language support:

- Eclipse
- IntelliJ IDEA
- VS Code (WIP)

> Before starting with any IDE, make sure you check the xref:ROOT:getting-started/01_system-requirements.adoc[System Requirements] page!

== Eclipse

Installing the JSL DSL plugin in Eclipse:

* Click btn:[Help] on the top of the application
* Select btn:[Install new software...]
* In the "Work with" input box, paste the following URL: `https://nexus.judo.technology/repository/p2/judo-meta-jsl/1.0.1.20221026_132128_2abe9779_develop`
* Click btn:[Add]
  * Name: Can be anything, e.g.: "JUDO JSL"
  * Location: Should be filled in, if not, paste it again from the above
* Select all items in the list
* Click btn:[Next] in every dialog, if prompted, accept all licenses
* When the "Trust" dialog opens up, select "Always trust all content", and click "Trust Selected"
* When prompted, click btn:[Restart Now]

> The URL for the plugin is only an example, the list of plugin releases can be found at the https://github.com/BlackBeltTechnology/judo-meta-jsl/releases[judo-meta-jsl] Releases page.

=== First time setup

When we first create a `.jsl` file, Eclipse will bring up a prompt "Configure Xtext".

In this prompt check the btn:[Remember my decision] option and click btn:[Yes].

=== PlantUML Support

PlantUML Diagrams are supported in Eclipse. This feature relies on Graphviz, which needs to be installed on your machine.

Installation instructions for Graphviz can be found at:

https://www.graphviz.org/download/

**Troubleshooting:**

If diagrams are not displayed, you need to update the PlantUML Settings in Eclipse, by providing the "Path to the dot executable".

You can use the following command to get the correct location of `dot`.

```
which dot
```

== Intellij IDEA

Our IntelliJ IDEA plugin is a TextMate plugin, which currently only supports syntax highlighting.

Additional functionality such as Code completion is in the works. In fact the support for the platform should be expected
to be improved continuously so stay tuned for updates!

Installation instructions could be found in the plugin's https://github.com/BlackBeltTechnology/jsl.tmbundle/blob/develop/doc/install-idea.adoc[Github Repository,window=_blank].

== VS Code

The VS Code plugin is a TextMate plugin, which supports syntax highlighting and parser (Xtext Server).

Installation instructions can be found in the plugin's https://github.com/BlackBeltTechnology/judo-jsl-vscode[Github Repository,window=_blank].